apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deploy
  labels:
    app: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      labels:
        app: production
    spec:
      containers:
      - name: github-website
        image: hanuman8698/github_website
        ports:
        - containerPort: 80